### ISSUE TITLE
Проверять существование юзера и логин(это про интеграцию)

### ISSUE THREAD

**Issue by dyakovri** [profcomff/auth-lib#2]
From [Сервис авторизации#13](https://github.com/profcomff/.github/issues/13)

**Comment by grigoriev-semyon** [comment]
Чек токена True/False 
Чек логина+пароля
Разлогиниться

**Comment by grigoriev-semyon** [comment]
Ci+setup.py

**Comment by grigoriev-semyon** [comment]
mount or middleware для Depends чтобы редиректить на админку

**Comment by grigoriev-semyon** [comment]
https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/

**Comment by grigoriev-semyon** [comment]
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm

**Comment by grigoriev-semyon** [comment]
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="https://auth.api.test.profcomff.com/email/login")

**Comment by dyakovri** [comment]
Про использование OAuth2 в фастапи

https://github.com/tiangolo/fastapi/issues/12#issuecomment-457706256

OAuth2 receives a flows parameter with your OAuth 2.0 flows, you can define them as a simple dictionary, but also using the included Pydantic models...

FastAPI, although not documented, includes Pydantic models for the whole OpenAPI 3.0 spec, this might help you if you want to use completion, etc during development. And it includes, of course, all the models for OAuth 2.0 flows, etc. You can use them from here: https://github.com/tiangolo/fastapi/blob/master/fastapi/openapi/models.py#L291

There are models for all the OAuth 2.0 flows, also made to match the OpenAPI 3.0 spec (and the way it's sub-divided in sections):
- OAuthFlowImplicit: ✔️ this is the one where your frontend gets the token directly with the authentication. And then sends it to the FastAPI backend.
- OAuthFlowPassword: ❌ this probably doesn't apply to you, because the frontend sends the password to Hydra directly, not to FastAPI.
- OAuthFlowClientCredentials: ❌ I guess this doesn't apply either, as your public frontend is the one authenticating your users, not a secure backend.
- OAuthFlowAuthorizationCode: ✔️ this is when your frontend gets a "code" that sends to your FastAPI backend, and then your FastAPI backend uses that code with secret client credentials to call Hydra to get a token that it can actually use to perform operations (again calling Hydra) like authenticating and getting user info. This is the most complex flow.
